# Server
server.port=8080
server.servlet.context-path=/KAI

## Spring ##
spring.application.name=kai-reptile
spring.http.encoding.enabled=true
spring.http.encoding.charset=utf-8

# LINE Bot
line.bot.channelToken=y3IIYETrlVPtxqc/JsnKTnfHgePBzOMB+D/FGfJaVpbjdDAYYAO7LkYfoaIxfnpYJZnJ3P+iNQDJTfj+gKkbiZmXRhVnhX/e12K5DMmGcvmsaQT0yBSxTwrLy/Fs2h0Us0n/dBrlGTeswErQYhd1ogdB04t89/1O/w1cDnyilFU=
line.bot.channelSecret=79ad873a1cedb7dd4879e3d7c1fbb27d
line.bot.handler.path=/line/callback

